window.INFETTI_READY.then(()=>{
const D=window.INFETTI_DATA,T=n=>D.teams.find(t=>t.name===n),pages=[["home","Home"],["league","League"],["fixtures","Fixtures"],["results","Results"],["scorers","Top Scorers"],["awards","Match Awards"],["cup","Cup"],["supercup","Super Cup"],["teams","Teams"]];
function club(n,a=0){let t=T(n);return `<div class="club ${a?"away":""}">${a?n:""}<img class="badge" src="${t.logo}">${a?"":n}</div>`}function matches(a){return a.length?a.map(m=>`<div class="match">${club(m.home)}<div class="ko"><strong>${m.time}</strong><small>${m.date}</small></div>${club(m.away,1)}</div>`).join(""):`<div class="empty">No fixtures yet.</div>`}function results(a){return a.length?a.map(m=>`<div class="match">${club(m.home)}<div class="ko"><strong>${m.hg} – ${m.ag}</strong><small>FULL TIME</small></div>${club(m.away,1)}</div>`).join(""):`<div class="empty">No results yet.<br>Scores will appear after the first matchday.</div>`}
function standings(){let s={};D.teams.forEach(t=>s[t.name]={n:t.name,p:0,w:0,d:0,l:0,gf:0,ga:0,pts:0});D.results.forEach(m=>{let h=s[m.home],a=s[m.away];h.p++;a.p++;h.gf+=m.hg;h.ga+=m.ag;a.gf+=m.ag;a.ga+=m.hg;if(m.hg>m.ag){h.w++;a.l++;h.pts+=3}else if(m.hg<m.ag){a.w++;h.l++;a.pts+=3}else{h.d++;a.d++;h.pts++;a.pts++}});return Object.values(s).sort((a,b)=>b.pts-a.pts||(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf)}
function table(){return `<table><thead><tr><th>POS</th><th>CLUB</th><th>P</th><th>W</th><th>D</th><th>L</th><th>GF</th><th>GA</th><th>GD</th><th>PTS</th></tr></thead><tbody>${standings().map((x,i)=>`<tr><td class="rank">${i+1}</td><td><div class="teamcell"><img src="${T(x.n).logo}">${x.n}</div></td><td>${x.p}</td><td>${x.w}</td><td>${x.d}</td><td>${x.l}</td><td>${x.gf}</td><td>${x.ga}</td><td>${x.gf-x.ga}</td><td class="pts">${x.pts}</td></tr>`).join("")}</tbody></table>`}
function leaders(a,label){return a.length?`<table><thead><tr><th>#</th><th>PLAYER</th><th>TEAM</th><th>${label}</th></tr></thead><tbody>${a.map((x,i)=>`<tr><td>${i+1}</td><td>${x.player}</td><td>${x.team}</td><td class="pts">${x.total}</td></tr>`).join("")}</tbody></table>`:`<div class="empty">No statistics yet.</div>`}
let nav=document.querySelector("#nav");pages.forEach(([id,l],i)=>{let b=document.createElement("button");b.textContent=l;b.className=i?"":"active";b.onclick=()=>{document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));document.querySelectorAll("#nav button").forEach(x=>x.classList.remove("active"));document.querySelector("#"+id).classList.add("active");b.classList.add("active");scrollTo({top:720,behavior:"smooth"})};nav.appendChild(b)});
next.innerHTML=matches(D.fixtures.filter(x=>x.round===1));latest.innerHTML=results(D.results.slice(-5).reverse());tableHome.innerHTML=tableLeague.innerHTML=table();scoreHome.innerHTML=leaders(D.leagueScorers,"GOALS");potgHome.innerHTML=leaders(D.potg,"AWARDS");kotgHome.innerHTML=leaders(D.kotg,"AWARDS");leagueScores.innerHTML=leaders(D.leagueScorers,"GOALS");cupScores.innerHTML=leaders(D.cupScorers,"GOALS");potg.innerHTML=leaders(D.potg,"AWARDS");kotg.innerHTML=leaders(D.kotg,"AWARDS");allResults.innerHTML=results(D.results);
teamStrip.innerHTML=D.teams.map(t=>`<div><img src="${t.logo}"><span>${t.short}</span></div>`).join("");teamsGrid.innerHTML=D.teams.map(t=>`<div class="teamcard"><img src="${t.logo}"><h3>${t.name}</h3><small>${t.short}</small></div>`).join("");
let fr="";for(let r=1;r<=18;r++)fr+=`<div class="round"><div class="roundtitle">MATCHWEEK ${r}</div><article class="panel">${matches(D.fixtures.filter(x=>x.round===r))}</article></div>`;fixtureRounds.innerHTML=fr;
}).catch(err=>{
  console.error("Google Sheet connection failed:",err);
  document.body.insertAdjacentHTML("afterbegin",
    '<div style="position:fixed;z-index:9999;left:12px;right:12px;bottom:12px;padding:12px 16px;background:#5b1717;color:white;border-radius:8px;font:600 14px Arial">Google Sheet data could not be loaded. Check that the spreadsheet is shared as Anyone with the link — Viewer and that the tab names have not changed.</div>');
});
